sudo: false
language: node_js
node_js:
- '6.1'
branches:
  only:
  - master
script:
- ./scripts/deploy.sh
env:
  global:
    secure: 2HFJe6TEauFejdXJ+ErFKaYgfgu5cML/GfczTsGRJz3kGMjZRNl0bZoPvIab6kDH0f7It57sjRsFZNsuOFlY2qMyuXuTQAmyxF/X5JB3+USX19lHZKP0eQHVwpAcFyMYLQ8u0syyXiv/z4OPZRZ9uzEOCKa3/q0OSfGQoh3gM6CBa16h0x8oFXjnkhrVUYqYslHvNEyCMNnz4KIM1kLho+lH0yanNcC9M52YTRDxOcYGN9EfwU6c5IbYKOTN3cn/y94tRbfpkg94GtgaHKZx97HLEeGCy0oU+fTW2alt4X49S6YpK8TQAv+blDe5w26/A+RZuM7bRQ0AMx0FK+vAZPKTuLK6anx3ucbrEX/QUgkml9208/b3D9lGe8n0GP31dQI2PhTTUsAxCLU6TXhYnzkfy9u7XigxBKzvitibZCyf9PWQIFEkntSDR8uerccvnuArCS+Yft6qCYhpSvIJlmTEweEbkLD+W8tAL9DeRWsr4XjhNAxsnKIwknvDjt16sanezPwW1WfP1EzuXVKkTdom82QPNrCJ9+brYly4AoTb6/utXEiScUAkehspygU/91cU5KWh4zaLnuAmD8i97Df7MxZZts29LyzcuM77Ie/CqWl7bDnYJzoV5qMT3W8PvqZwzzvFQsL4BRnlJ1fX2Eeq/Rs0kCFek6FyFukRO14=