// flow-typed signature: 5160b970fa66318bafa010264abd22dc
// flow-typed version: <<STUB>>/typeface-open-sans_v^0.0.22/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-open-sans'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-open-sans' {
  declare module.exports: any;
}
